name: form_challenge
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.4"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  # Core
  fluttertoast: ^8.0.9
  google_fonts: ^2.3.1
  kartal: ^2.3.1
  # State
  provider: ^6.0.2
  #Cache
  shared_preferences: ^2.0.13


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
